[package]
name = "rust"
version = "0.1.0"
authors = ["Phablulo <phablulo@live.com>"]
edition = "2018"

[dependencies]
image = "0.21"
rand = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"